### PR TITLE
Fixed iOS version limit to allow the tweak to run on iOS 11.

### PR DESCRIPTION
**Pull request by gilshahar7**
Hey. this is working great on iOS 11 using the original 10.xm so i changed the version checking to allow it to run on any iOS version above 10.0

### CODE REVIEW

**Comment by ahyattdev** [comment]
Hey Gil,

That’s great, I have not had a jailbroken device for a couple years, I didn’t realize that it works for iOS 11 without any code changes.

We will get this in soon. What device are you on that it works for? I would like it to be tested on iPhone and iPad for iOS 11 before doing a release.

I at one point I tried running TypeTab in the iOS 11 simulator (after modifying the code to remove the version check) and it caused Safari to crash, so I would like to do some testing before thinking it fully works.

Also, I'm kind of out of the loop, do you know if there is an iOS 12 jailbreak available?

Thank you for your help!

**Comment by gilshahar7** [comment]
I tested on iOS 11 with an iPhone X.

I also uploaded it to a main repo (Packix) and i have not heared any issues
from users.

iOS 12 jailbreak (12.0 - 12.1.2) is almost done, there is a rootlessJB by
Jake James. It does not have cydia and tweaks are only working after
patching the dylib and installing manually.

And there is no root :P

**Comment by ahyattdev** [comment]
Thanks for figuring out that there aren't any big changes needed for it to work. It must have been crashing on the simulator for me for a reason related to the simject tool.

I finally got around to jailbreaking an old device on 12.1 and TypeTab works on it. I have put a deb under the releases page of this repository. Could you verify that it works on iOS 11?

Thanks again for your help! After verifying that this build also works on iOS 11 I will push an update to big boss.

**Comment by ahyattdev** [comment]
Here is the link https://github.com/ahyattdev/typetab/releases/tag/v4.0

**Pull request closed without merging**
